/* create database sk;

drop table if exists public.tempo_applications;

create table public.tempo_applications (
        application_date date,
        loan_application_id int,
        loan_number int,
        decision varchar(20),
        amount_requested decimal(15,2),
        maximum_loan_amount decimal(15,2),
        funded_flag varchar(10),
        funded_on date,
        funded_amount decimal(15,2),  
        credit_score_id int,
        monthly_hh_income decimal(15,2),
        annualized_hh_income decimal(15,2),
        fico_score int,
        stream_score decimal(10, 8),
        bankruptcy_score int,
        personal_loan_risk int,
        new_account_score int,
        vantage_score int,
        debt_to_income decimal(10,3),
        g235s int,
        g001s int,
        us06s int,
        g202a int,
        fi33s int,
        in20s int,
        br06s int,
        mt01s int,
        bi27s int,
        g051s int,
        g960s int,
        g403s int,
        atap01 int,
        installment_current_balance decimal(15,2),
        installment_high_credit decimal(15,2),
        installment_monthly_payment decimal(15,2),
        installment_late_60_days int,
        installment_past_due_amount decimal(15,2),
        installment_count int,
        revolving_current_balance decimal(15,2),
        revolving_high_credit decimal(15,2),
        revolving_monthly_payment decimal(15,2),
        revolving_late_60_days int,
        revolving_past_due_amount decimal(15,2),
        revolving_count int,
        mortgage_current_balance decimal(15,2),
        mortgage_max_current_balance decimal(15,2),
        mortgage_high_credit decimal(15,2),
        mortgage_monthly_payment decimal(15,2),
        mortgage_late_60_days int,
        mortgage_past_due_amount decimal(15,2),
        mortgage_count int,
        loc_current_balance decimal(15,2),
        loc_high_credit decimal(15,2),
        loc_monthly_payment decimal(15,2),
        loc_late_60_days int,
        loc_past_due_amount decimal(15,2),
        loc_count int,
        closed_with_balance_current_balance decimal(15,2),
        closed_with_balance_high_credit decimal(15,2),
        closed_with_balance_monthly_payment decimal(15,2),
        closed_with_balance_late_60_days int,
        closed_with_balance_past_due_amount decimal(15,2),
        closed_with_balance_count int,
        unsecured_current_balance decimal(15,2),
        unsecured_high_credit decimal(15,2),
        unsecured_monthly_payment decimal(15,2),
        unsecured_late_60_days int,
        unsecured_past_due_amount decimal(15,2),
        unsecured_trade_count int,
        credit_card_current_balance decimal(15,2),
        credit_card_high_credit decimal(15,2),
        credit_card_monthly_payment decimal(15,2),
        credit_card_late_60_days int,
        credit_card_past_due_amount decimal(15,2),
        credit_card_trade_count int,
        student_loans_current_balance decimal(15,2),
        student_loans_high_credit decimal(15,2),
        student_loans_monthly_payment decimal(15,2),
        student_loans_late_60_days int,
        student_loans_past_due_amount decimal(15,2),
        student_loans_trade_count int,
        total_current_balance decimal(15,2),
        total_high_credit decimal(15,2),
        total_monthly_payment decimal(15,2),
        mortgage_latest_open_date date,
        city varchar(50),
        state varchar(2),
        territory varchar(50),
        property_assessment_value decimal(15,2),
        property_avm_value decimal(15,2),
        loan_type varchar(20),
        term int,
        interest_rate decimal(5,2),
        orig_term int,
        orig_interest_rate decimal(5,2)
);  */

--  cp /Users/sagar.kalyankar/Desktop/kachra/tempoApr26+.csv /tmp/
delete from public.tempo_applications where application_date >='2026-04-01';

COPY public.tempo_applications 
FROM '/tmp/tempoApr26+.csv' 
WITH (
        FORMAT CSV, 
        HEADER TRUE, 
        NULL '', 
        FORCE_NULL (
                application_date,
                loan_application_id,
                loan_number,
                decision,
                amount_requested,
                maximum_loan_amount,
                funded_flag,
                funded_on,
                funded_amount,
                credit_score_id,
                monthly_hh_income,
                annualized_hh_income,
                fico_score,
                stream_score,
                bankruptcy_score,
                personal_loan_risk,
                new_account_score,
                vantage_score,
                debt_to_income,
                g235s,
                g001s,
                us06s,
                g202a,
                fi33s,
                in20s,
                br06s,
                mt01s,
                bi27s,
                g051s,
                g960s,
                g403s,
                atap01,
                installment_current_balance,
                installment_high_credit,
                installment_monthly_payment,
                installment_late_60_days,
                installment_past_due_amount,
                installment_count,
                revolving_current_balance,
                revolving_high_credit,
                revolving_monthly_payment,
                revolving_late_60_days,
                revolving_past_due_amount,
                revolving_count,
                mortgage_current_balance,
                mortgage_max_current_balance,
                mortgage_high_credit,
                mortgage_monthly_payment,
                mortgage_late_60_days,
                mortgage_past_due_amount,
                mortgage_count,
                loc_current_balance,
                loc_high_credit,
                loc_monthly_payment,
                loc_late_60_days,
                loc_past_due_amount,
                loc_count,
                closed_with_balance_current_balance,
                closed_with_balance_high_credit,
                closed_with_balance_monthly_payment,
                closed_with_balance_late_60_days,
                closed_with_balance_past_due_amount,
                closed_with_balance_count,
                unsecured_current_balance,
                unsecured_high_credit,
                unsecured_monthly_payment,
                unsecured_late_60_days,
                unsecured_past_due_amount,
                unsecured_trade_count,
                credit_card_current_balance,
                credit_card_high_credit,
                credit_card_monthly_payment,
                credit_card_late_60_days,
                credit_card_past_due_amount,
                credit_card_trade_count,
                student_loans_current_balance,
                student_loans_high_credit,
                student_loans_monthly_payment,
                student_loans_late_60_days,
                student_loans_past_due_amount,
                student_loans_trade_count,
                total_current_balance,
                total_high_credit,
                total_monthly_payment,
                mortgage_latest_open_date,
                city,
                state,
                territory,
                property_assessment_value,
                property_avm_value,
                loan_type,
                term,
                interest_rate,
                orig_term,
                orig_interest_rate
        )
);
